version: 2.1
orbs:
  node: circleci/node@3.0.0
  discord: teka23/discord@0.0.1
  codecov: codecov/codecov@1.1.1

workflows:
  test:
    jobs:
      - node/test
      - discord/status:
          only_for_branches: main
