version: 2.1
orbs:
  node: circleci/node@3.0.0
  discord: teka23/discord@0.0.1
  codecov: codecov/codecov@1.1.1

jobs:
  notify:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - discord/status

workflows:
  build-deploy:
    jobs:
      - node/test
      - notify