version: 2.1
orbs:
  node: circleci/node@4.1.0
  discord: antonioned/discord@0.1.0

jobs:
  deploy:
    docker:
      - image: 'google/cloud-sdk'
    steps:
      - run: git clone $CIRCLE_REPOSITORY_URL
      - run: echo 'runtime:' $'nodejs12\nenv_variables:\n REMOTE_LOGGER_URL:'' '${REMOTE_LOGGER_URL} >app.yaml
      - run: |
          echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
          gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          gcloud --quiet app deploy
      - discord/status:
          failure_message: "Triggered by: **${CIRCLE_USERNAME}** \\n\\n Ooops! The ${CIRCLE_PULL_REQUEST} deploy has failed!"
          success_message: "Triggered by: **${CIRCLE_USERNAME}** \\n\\n Wow! The ${CIRCLE_PULL_REQUEST} deploy has succeed!"
 
workflows:
  build-deploy:
    jobs:
      - node/test:
        run-command: test:unit
        filters:
            branches:
              only: main         
      - deploy:
          requires:
              - node/test