version: 2.1
orbs:
  node: circleci/node@3.0.0
  slack: circleci/slack@4.0
  codecov: codecov/codecov@1.1.1
jobs:
  notify:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "*This is a text notification*",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: always
  deploy:
workflows:
  test:
    jobs:
      - node/test
      - deploy
      - notify:
          context: slack-secrets
